algoritmo "19-notas-media"
// Função :Curso em video
// Autor :Caio Rodegheri
// Data : 13/06/2023
// Seção de Declarações 
var
nome:caractere
n1,n2,M:Real
inicio
 Escreva("Digite seu nome: ")
 leia(nome)
 Escreva("Digite sua primeira nota: ")
 Leia(n1)
 Escreva("Digite sua segunda nota: ")
 Leia(n2)
 m<-(n1+n2)/2
 Escreval(Nome, " sua media final foi de: ", M, "")
 se M>=7 entao
    Escreva("Parabens! Voce foi aprovado.")
 fimse
fimalgoritmo

