algoritmo "26-comparar-numero"
// Função :Curso em video
// Autor :Caio Rodegheri
// Data : 13/06/2023
// Seção de Declarações
var
n1,n2:real
inicio
Escreva("Digite o primeiro numero: ")
leia(n1)
Escreva("Digite o segundo numero: ")
leia(n2)
Se n1>n2 entao
   escreva("O primeiro valor é o maior")
senao
   se n1<n2 entao
      escreva("O segundo valor e o maior")
   senao
      se n1=n2 entao
         escreva("Nao existe valor maior, os dois sao iguais")
      fimse
   fimse
fimse
fimalgoritmo
