algoritmo "ParOuImparProcedimento"
// Função :Curso em video
// Autor :Caio Rodegheri
// Data : 13/06/2023
// Seção de Declarações
var
N:inteiro
procedimento Parouimpar(v: inteiro)
inicio
EscrevaL("O valor de V e ", V)
EscrevaL("O valor de N e ", N)
se(v%2=0) entao
   Escreval("O numero ", v, " e par")
senao
   escreval("O numero ", v," e impar")
fimse
fimprocedimento
inicio
Escreva("Digite um numero: ")
leia(N)
Parouimpar(N)
fimalgoritmo

